---
- name: Create authentik database user
  community.postgresql.postgresql_user:
    name: "{{ authentik_db_user }}"
    password: "{{ authentik_db_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
  become_user: postgres

- name: Create authentik database
  community.postgresql.postgresql_db:
    name: "{{ authentik_db_name }}"
    owner: "{{ authentik_db_user }}"
    encoding: UTF8
    template: template0
  become_user: postgres
