---
- name: Install PostgreSQL and psycopg2
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - python3-psycopg2
    state: present
    update_cache: true

- name: Enable and start postgresql service
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started

- name: Set listen_addresses in postgresql.conf
  ansible.builtin.lineinfile:
    path: "{{ postgresql_config_dir }}/postgresql.conf"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '{{ postgresql_listen_addresses }}'"
  notify: restart postgresql
