- name: Install Redis
  apt:
    name:
      - redis-server
      - php-redis
    state: present

- name: Bind Redis to localhost
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 127.0.0.1'
  notify: Restart Redis
