---
traefik_version: "v3.7.0-ea.3"
traefik_domain: "magbanua.xyz"
traefik_acme_email: "sysadmin@magbanua.xyz"

vaultwarden_ip: "10.10.200.41"
vaultwarden_port: 80
wikijs_ip: "10.10.200.43"
wikijs_port: 3000

traefik_dashboard_host: "traefik.{{ traefik_domain }}"

grafana_ip: "10.10.200.22"
grafana_port: 3000
