---
- name: Download and install k3s server
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"

- name: Enable and start k3s service
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    state: started
    daemon_reload: true

- name: Wait for node token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 60

- name: Label control-plane node
  ansible.builtin.command:
    cmd: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/control-plane=true --overwrite
  changed_when: false
