---
# Installs PostgreSQL 16.
#
# Usage:
#   ansible-playbook playbooks/LXC/setup-postgresql.yml

- name: Install and configure PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  roles:
    - postgresql
