---
prometheus_version: "3.2.1"
prometheus_install_dir: "/usr/local/bin"
prometheus_config_path: "/etc/prometheus"
prometheus_storage_path: "/var/lib/prometheus"
prometheus_retention: "15d"
prometheus_port: 9090

alertmanager_ip: "10.10.200.21"
alertmanager_port: 9093

traefik_ip: "10.10.200.10"
traefik_metrics_port: 8080

cadvisor_ip: "10.10.200.50"
cadvisor_port: 8080

node_exporter_port: 9100
node_exporter_targets:
  - host: traefik
    ip: "10.10.200.10"
  - host: prometheus
    ip: "10.10.200.20"
  - host: alertmanager
    ip: "10.10.200.21"
  - host: grafana
    ip: "10.10.200.22"
  - host: loki
    ip: "10.10.200.23"
  - host: alloy
    ip: "10.10.200.24"
  - host: apt-cacher-ng
    ip: "10.10.200.4"
  - host: jump-host
    ip: "10.10.200.3"
  - host: postgresql
    ip: "10.10.200.30"
  - host: redis
    ip: "10.10.200.31"
  - host: docker-host
    ip: "10.10.200.50"
